### ISSUE TITLE
Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by anhldbk** [thomascsd/vscode-readme-pattern#5]
Hi Thomas,

Thank you for this useful extension. I've installed your ext but could NOT run. Here are my error log:

```log
[2020-09-02 11:38:25.700] [exthost] [error] TypeError: Cannot read property 'path' of undefined
    at /Users/whoami/.vscode/extensions/thomascsd.vscode-readme-pattern-1.3.0/out/extension.js:14:135
    at _executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:642:374)
    at _.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:642:749)
    at m._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:819:926)
    at m._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:819:618)
    at m._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:818:252)
    at m._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:817:6)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:815:161
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:222)
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:239:494)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1007:179
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:222)
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:239:494)
    at t.PersistentProtocol._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:244:17)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:241:67
    at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:222)
    at p.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:236:949)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:236:301
    at Socket.t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:245:572)
    at Socket.emit (events.js:203:13)
    at Socket.EventEmitter.emit (domain.js:476:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17) extension.readmeOnExplorer
```

Look like the error is from the following code block: https://github.com/thomascsd/vscode-readme-pattern/blob/1021e5c94081f52c12f7ea8bc002b8b88ddf2a76/src/extension.ts#L17-L21

Would you pls have a look at this error? 

Thank in advance.

**Comment by thomascsd** [comment]
Thanks for reply
I will fix it ASAP

**Comment by thomascsd** [comment]
Hi Andy
Could you give me more info about your project
For example, folder structure, folder info that you want create README.md

Thanks

**Comment by anhldbk** [comment]
@thomascsd There's no special structure, even in an empty directory

<img width="1440" alt="Screen Shot 2020-09-05 at 14 06 49" src="https://user-images.githubusercontent.com/3270746/92299937-0ca23c80-ef81-11ea-87a8-e7c47e53eb6b.png">

**Comment by thomascsd** [comment]
@anhldbk Press F1 -> input readme -> select "readme: Generates README.md", following image, is it works?

![image](https://user-images.githubusercontent.com/7641666/92306753-21ec8a80-efc4-11ea-8c7a-c8bae5776f80.png)

**Comment by anhldbk** [comment]
@thomascsd My bad. I selected `Generated README.md on here`.

**Comment by thomascsd** [comment]
To prevent confusion, I'll set ``Generated README.md on here``that not show in command palette
thanks

**Comment by anhldbk** [comment]
@thomascsd Thank you.
